# Generated by Django 4.2.3 on 2023-07-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
