# Generated by Django 4.2.3 on 2023-07-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Tienda'),
        ),
    ]
