# Generated by Django 4.2.3 on 2023-07-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_member_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
    ]
